#!/usr/bin/env python3

from vend import Merch
import argparse

PARSER = argparse.ArgumentParser()
PARSER.add_argument("position")
ARGS = PARSER.parse_args()

merch = Merch()
merch.vend(ARGS.position[0].upper(), int(ARGS.position[1]))